/*
Create empty table with ID=bigint, name=varchar
*/
drop table if exists member CASCADE;
create table member
(
    id   bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);